openapi: "3.0.2"
info:
  version: 1.0.0
  title: API Payment
  description: >
    **Service responsible for payments**
paths:
  /payment:
    post:
      tags:
        - Payment
      summary: Create new payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  description: Order ID
      responses:
        200:
          description: Created currectly
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/PaymentSchema"
                  message:
                    type: string
                    description: Sucess
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
  /payment/process:
    post:
      tags:
        - Payment
      summary: Process payment - Change status to paid or not paid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentId:
                  type: string
                  description: Payment ID
                status:
                  type: string
                  description: new status for the payment
      responses:
        200:
          description: Processed correctly
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/PaymentSchema"
                  message:
                    type: string
                    description: Sucess
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    PaymentSchema:
      type: object
      description: Full properties of a payment.
      properties:
        id:
          type: string
          description: payment id.
        orderId:
          type: string
          description: order id.
        status:
          type: string
          description: payment status.
        code:
          type: string
          description: payment generated code
  responses:
    BadRequest:
      description: Invalid Request
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Describes a message informing a reason for the error
                example: "Email required"
    NotFound:
      description: Entity not found
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Entity not found
                example: "Not Found"
    InternalServerError:
      description: Internal server error
      content:
        "application/json":
          schema:
            properties:
              data:
                type: object
                properties:
                  stack:
                    type: string
              message:
                type: string
                title: Error message
                description: Describes a message informing a reason for the error
                example: "Internal Server Error"
